services:
  ctrl-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ctrl-frontend:latest
    container_name: ctrl-frontend
    restart: always
    ports:
      - "5173:5173"
    env_file:
      - .env
    networks:
      - ctrl-shared-net

networks:
  ctrl-shared-net:
    external: true
