apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.frontendService.name }}-pdb
spec:
  minAvailable: {{ default 1 .Values.frontendService.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: app-{{ .Values.frontendService.name }}
