apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.frontendService.name }}-svc
    labels:
        chart: '{{ template "name" . }}-{{ .Chart.Version | replace "+" "_" }}'
    annotations:
        alb.ingress.kubernetes.io/healthcheck-port: "{{ .Values.frontendService.internalPort }}"
spec:
    type: {{ .Values.frontendService.type }}
    ports:
        -
            port: {{ .Values.frontendService.externalPort }}
            targetPort: {{ .Values.frontendService.internalPort }}
            name: http
            protocol: TCP
    selector:
        app.kubernetes.io/name: app-{{ .Values.frontendService.name }}
